Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/trusty64"
    config.vm.box_url = "ubuntu/trusty64"

	config.vm.provider :virtualbox do |vb|
    	vb.name = "SLiSW-Clojure"
  		#   vb.customize ["modifyvm", :id, "--memory", "1024"]
 	end

	config.vm.synced_folder "../../../", "/home/vagrant/code"

  	config.vm.network :forwarded_port, guest: 80, host: 8070

    config.vm.provision :fabric do |fabric|
        fabric.fabfile_path = "../fabfile.py"
        fabric.tasks = ["ubuntu_update"]
    end
end