Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/trusty64"
    config.vm.box_url = "ubuntu/trusty64"

    config.vm.synced_folder "../../", "/home/vagrant/code"

    config.vm.provider :virtualbox do |vb|
        vb.name = "AngularStudies"
        #   vb.customize ["modifyvm", :id, "--memory", "1024"]
    end

    config.vm.network "forwarded_port", guest: 80, host: 8070

    config.vm.provision :fabric do |fabric|
        fabric.fabfile_path = "../fabfile.py"
        fabric.tasks = ["ubuntu_update", "install_nginx", "configure_nginx"]
    end
end